version: '3.5'

services:
            
  service-app1:
    image: nexus.ezecomcorp.com:8443/app1:0.0.1
    ports:
      - 6001:80
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app2:
    image: nexus.ezecomcorp.com:8443/app2:0.0.0
    ports:
      - 6002:80
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app3:
    image: nexus.ezecomcorp.com:8443/app3:0.0.0
    ports:
      - 6003:80
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure


  haproxy:
    ports:
      - "80:80"
    image: nexus.ezecomcorp.com:8443/int-haproxy:0.0.0
    deploy:
      mode: global
      update_config:
        parallelism: 1

